// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYkmMb6Gl9aFxsn04JfSDcgvrZ3aklRqM',
    appId: '1:127906404801:web:cd8320c5c55a1368933740',
    messagingSenderId: '127906404801',
    projectId: 'p2p-car-rental-app',
    authDomain: 'p2p-car-rental-app.firebaseapp.com',
    storageBucket: 'p2p-car-rental-app.appspot.com',
    measurementId: 'G-RYJXQ1JK06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC26SufEr5sb-if5o2d14PBrwUoDtD0nsA',
    appId: '1:127906404801:android:18d279b0a8dc7d53933740',
    messagingSenderId: '127906404801',
    projectId: 'p2p-car-rental-app',
    storageBucket: 'p2p-car-rental-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ_4aroPOFpYgYI5e63Shl02VYB3cCG_0',
    appId: '1:127906404801:ios:4830bd272130ff38933740',
    messagingSenderId: '127906404801',
    projectId: 'p2p-car-rental-app',
    storageBucket: 'p2p-car-rental-app.appspot.com',
    iosBundleId: 'com.example.p2pRentingCarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ_4aroPOFpYgYI5e63Shl02VYB3cCG_0',
    appId: '1:127906404801:ios:8e8a7d7ece47ce4e933740',
    messagingSenderId: '127906404801',
    projectId: 'p2p-car-rental-app',
    storageBucket: 'p2p-car-rental-app.appspot.com',
    iosBundleId: 'com.example.p2pRentingCarApp.RunnerTests',
  );
}
